wandb_version: 1

data:
  desc: null
  value: 'True'
data_dir:
  desc: null
  value: /home/fish/Documents/imagenet
dataset:
  desc: null
  value: ''
train_split:
  desc: null
  value: train
val_split:
  desc: null
  value: validation
dataset_download:
  desc: null
  value: false
class_map:
  desc: null
  value: ''
model:
  desc: null
  value: deit_small_patch16_224
pretrained:
  desc: null
  value: false
initial_checkpoint:
  desc: null
  value: ''
resume:
  desc: null
  value: ''
no_resume_opt:
  desc: null
  value: false
num_classes:
  desc: null
  value: 1000
gp:
  desc: null
  value: null
img_size:
  desc: null
  value: null
in_chans:
  desc: null
  value: null
input_size:
  desc: null
  value: null
crop_pct:
  desc: null
  value: null
mean:
  desc: null
  value: null
std:
  desc: null
  value: null
interpolation:
  desc: null
  value: ''
batch_size:
  desc: null
  value: 128
validation_batch_size:
  desc: null
  value: null
channels_last:
  desc: null
  value: false
fuser:
  desc: null
  value: ''
grad_accum_steps:
  desc: null
  value: 1
grad_checkpointing:
  desc: null
  value: false
fast_norm:
  desc: null
  value: false
model_kwargs:
  desc: null
  value: {}
head_init_scale:
  desc: null
  value: null
head_init_bias:
  desc: null
  value: null
torchscript:
  desc: null
  value: false
torchcompile:
  desc: null
  value: null
opt:
  desc: null
  value: sgd
opt_eps:
  desc: null
  value: null
opt_betas:
  desc: null
  value: null
momentum:
  desc: null
  value: 0.9
weight_decay:
  desc: null
  value: 2.0e-05
clip_grad:
  desc: null
  value: null
clip_mode:
  desc: null
  value: norm
layer_decay:
  desc: null
  value: null
opt_kwargs:
  desc: null
  value: {}
sched:
  desc: null
  value: cosine
sched_on_updates:
  desc: null
  value: false
lr:
  desc: null
  value: 0.05
lr_base:
  desc: null
  value: 0.1
lr_base_size:
  desc: null
  value: 256
lr_base_scale:
  desc: null
  value: linear
lr_noise:
  desc: null
  value: null
lr_noise_pct:
  desc: null
  value: 0.67
lr_noise_std:
  desc: null
  value: 1.0
lr_cycle_mul:
  desc: null
  value: 1.0
lr_cycle_decay:
  desc: null
  value: 0.5
lr_cycle_limit:
  desc: null
  value: 1
lr_k_decay:
  desc: null
  value: 1.0
warmup_lr:
  desc: null
  value: 1.0e-05
min_lr:
  desc: null
  value: 0
epochs:
  desc: null
  value: 16
epoch_repeats:
  desc: null
  value: 0.0
start_epoch:
  desc: null
  value: null
decay_milestones:
  desc: null
  value:
  - 90
  - 180
  - 270
decay_epochs:
  desc: null
  value: 90
warmup_epochs:
  desc: null
  value: 1
warmup_prefix:
  desc: null
  value: false
cooldown_epochs:
  desc: null
  value: 0
patience_epochs:
  desc: null
  value: 10
decay_rate:
  desc: null
  value: 0.1
no_aug:
  desc: null
  value: false
scale:
  desc: null
  value:
  - 0.08
  - 1.0
ratio:
  desc: null
  value:
  - 0.75
  - 1.3333333333333333
hflip:
  desc: null
  value: 0.5
vflip:
  desc: null
  value: 0.0
color_jitter:
  desc: null
  value: 0.4
aa:
  desc: null
  value: null
aug_repeats:
  desc: null
  value: 0
aug_splits:
  desc: null
  value: 0
jsd_loss:
  desc: null
  value: false
bce_loss:
  desc: null
  value: false
bce_target_thresh:
  desc: null
  value: null
reprob:
  desc: null
  value: 0.0
remode:
  desc: null
  value: pixel
recount:
  desc: null
  value: 1
resplit:
  desc: null
  value: false
mixup:
  desc: null
  value: 0.0
cutmix:
  desc: null
  value: 0.0
cutmix_minmax:
  desc: null
  value: null
mixup_prob:
  desc: null
  value: 1.0
mixup_switch_prob:
  desc: null
  value: 0.5
mixup_mode:
  desc: null
  value: batch
mixup_off_epoch:
  desc: null
  value: 0
smoothing:
  desc: null
  value: 0.1
train_interpolation:
  desc: null
  value: random
drop:
  desc: null
  value: 0.0
drop_connect:
  desc: null
  value: null
drop_path:
  desc: null
  value: null
drop_block:
  desc: null
  value: null
bn_momentum:
  desc: null
  value: null
bn_eps:
  desc: null
  value: null
sync_bn:
  desc: null
  value: false
dist_bn:
  desc: null
  value: reduce
split_bn:
  desc: null
  value: false
model_ema:
  desc: null
  value: false
model_ema_force_cpu:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.9998
seed:
  desc: null
  value: 42
worker_seeding:
  desc: null
  value: all
log_interval:
  desc: null
  value: 50
recovery_interval:
  desc: null
  value: 0
checkpoint_hist:
  desc: null
  value: 10
workers:
  desc: null
  value: 4
save_images:
  desc: null
  value: false
amp:
  desc: null
  value: false
amp_dtype:
  desc: null
  value: float16
amp_impl:
  desc: null
  value: native
no_ddp_bb:
  desc: null
  value: false
synchronize_step:
  desc: null
  value: false
pin_mem:
  desc: null
  value: false
no_prefetcher:
  desc: null
  value: false
output:
  desc: null
  value: ./output
experiment:
  desc: null
  value: timmtest
eval_metric:
  desc: null
  value: top1
tta:
  desc: null
  value: 0
local_rank:
  desc: null
  value: 0
use_multi_epochs_loader:
  desc: null
  value: false
log_wandb:
  desc: null
  value: true
prefetcher:
  desc: null
  value: true
distributed:
  desc: null
  value: false
world_size:
  desc: null
  value: 1
rank:
  desc: null
  value: 0
device:
  desc: null
  value: cuda:0
_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.2
    framework: huggingface
    huggingface_version: 4.29.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687895100.13387
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.10.11
      5: 0.15.2
      6: 4.29.2
      8:
      - 5
